<?php

namespace oihana\enums\http;

use oihana\reflect\traits\ConstantsTrait;

/**
 * Conventional PSR-7 request attribute names shared across packages.
 *
 * PSR-7 lets any middleware attach arbitrary key/value pairs to a request via {@see ServerRequestInterface::withAttribute()}.
 * Downstream consumers read those values with {@see ServerRequestInterface::getAttribute()}.
 *
 * The constants below standardise the keys used by middlewares (writers) and
 * controllers / traits (readers) so the convention is not duplicated as
 * string literals across packages.
 *
 * Values are camelCase to match the de-facto PSR-15 ecosystem convention
 * (e.g. Slim, Mezzio, league/route).
 *
 * @package oihana\enums\http
 * @author  Marc Alcaraz
 */
class RequestAttribute
{
    use ConstantsTrait ;

    // -------------------------------------------------------------------------
    // Identity / authentication
    // -------------------------------------------------------------------------

    /**
     * Raw access token string (without the scheme prefix) as received from
     * the `Authorization` header. Useful for token introspection,
     * downstream service calls (token relay), or refresh logic.
     */
    public const string ACCESS_TOKEN = 'accessToken' ;

    /**
     * Authentication scheme actually used to authenticate the request
     * (`Bearer`, `Basic`, `OAuth`, ...). See {@see AuthScheme}.
     */
    public const string AUTH_SCHEME = 'authScheme' ;

    /**
     * Token type returned by the authorization server (typically `Bearer`,
     * sometimes `DPoP`). See RFC 6749 §5.1 and RFC 9449.
     */
    public const string TOKEN_TYPE = 'tokenType' ;

    /**
     * Full set of decoded JWT claims, kept on the request so downstream
     * components can read provider-specific or rarely-used claims without
     * re-parsing the token.
     */
    public const string USER_CLAIMS = 'userClaims' ;

    /**
     * Stable identifier of the authenticated user (typically the Zitadel `sub` claim).
     * Posted by the authentication middleware after the JWT has been validated,
     * and read by every downstream component that needs to know "who is making this request"
     * (Casbin enforcement, audit log, capability gating, AQL projection authorizers, ...).
     */
    public const string USER_ID = 'userId' ;

    /**
     * Roles granted to the authenticated user (array of strings).
     * Typically populated from the JWT `roles` / `groups` claim or resolved
     * from an identity provider, and consumed by RBAC enforcement.
     */
    public const string USER_ROLES = 'userRoles' ;

    /**
     * OAuth 2.0 / OIDC scopes granted to the access token (array of strings).
     * Sourced from the `scope` / `scp` JWT claim and used to gate endpoints by scope.
     */
    public const string USER_SCOPES = 'userScopes' ;

    // -------------------------------------------------------------------------
    // Traceability
    // -------------------------------------------------------------------------

    /**
     * Correlation identifier propagated across services for end-to-end
     * tracing of a logical operation that spans several requests.
     */
    public const string CORRELATION_ID = 'correlationId' ;

    /**
     * Unique identifier of the incoming HTTP request, generated by an early
     * middleware. Echoed in responses (e.g. `X-Request-Id` header) and
     * persisted in audit / access logs.
     */
    public const string REQUEST_ID = 'requestId' ;

    /**
     * Distributed tracing identifier (W3C Trace Context `traceparent` or
     * OpenTelemetry trace id) attached to the request.
     */
    public const string TRACE_ID = 'traceId' ;

    // -------------------------------------------------------------------------
    // Multi-tenancy
    // -------------------------------------------------------------------------

    /**
     * Organization identifier (Zitadel-style `org_id`) under which the
     * authenticated user is acting for this request.
     */
    public const string ORGANIZATION_ID = 'organizationId' ;

    /**
     * Tenant identifier under which the request is executed. Used by
     * AQL projection authorizers and tenant-scoped resource lookups.
     */
    public const string TENANT_ID = 'tenantId' ;

    // -------------------------------------------------------------------------
    // Routing (PSR-15)
    // -------------------------------------------------------------------------

    /**
     * Matched route object/descriptor attached by the router middleware
     * (e.g. Slim `RouteInterface`, league/route `Route`).
     */
    public const string ROUTE = 'route' ;

    /**
     * Associative array of route parameters captured by the router
     * (e.g. `['id' => '42']` for `/users/{id}`).
     */
    public const string ROUTE_PARAMS = 'routeParams' ;

    // -------------------------------------------------------------------------
    // Internationalization
    // -------------------------------------------------------------------------

    /**
     * Resolved locale for the request (e.g. `fr_FR`, `en_US`), usually
     * negotiated from `Accept-Language` and/or user preferences.
     */
    public const string LOCALE = 'locale' ;
}
